package com.example.sgr.wzd.model.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.sgr.wzd.model.dbBean.Test;
import com.example.sgr.wzd.model.dbBean.NewsTitle;

import com.example.sgr.wzd.model.greendao.TestDao;
import com.example.sgr.wzd.model.greendao.NewsTitleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testDaoConfig;
    private final DaoConfig newsTitleDaoConfig;

    private final TestDao testDao;
    private final NewsTitleDao newsTitleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testDaoConfig = daoConfigMap.get(TestDao.class).clone();
        testDaoConfig.initIdentityScope(type);

        newsTitleDaoConfig = daoConfigMap.get(NewsTitleDao.class).clone();
        newsTitleDaoConfig.initIdentityScope(type);

        testDao = new TestDao(testDaoConfig, this);
        newsTitleDao = new NewsTitleDao(newsTitleDaoConfig, this);

        registerDao(Test.class, testDao);
        registerDao(NewsTitle.class, newsTitleDao);
    }
    
    public void clear() {
        testDaoConfig.clearIdentityScope();
        newsTitleDaoConfig.clearIdentityScope();
    }

    public TestDao getTestDao() {
        return testDao;
    }

    public NewsTitleDao getNewsTitleDao() {
        return newsTitleDao;
    }

}
